using UnityEngine;

public class Collectible : MonoBehaviour
{
    private Inventory inventory;   // Rķfķrence Ó l'inventaire du joueur
    private ItemData itemData;     // Rķfķrence Ó l'objet Ó ajouter Ó l'inventaire

    public void Setup(Inventory inventory, ItemData itemData)
    {
        this.inventory = inventory;
        this.itemData = itemData;
        GetComponent<SpriteRenderer>().sprite = itemData.icon;
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player")) // Vķrifie si le joueur entre en contact
        {
            // Vķrifie si l'objet peut Ļtre ajoutķ
            if (inventory.CanAddItem(itemData, 1))
            {
                inventory.AddItem(itemData, 1); // Ajoute 1 unitķ Ó l'inventaire
                Debug.Log($"Ramassķ : {itemData.itemName}");
                Destroy(gameObject); // Dķtruit le sprite ramassable
            }
            else
            {
                Debug.Log($"Pas assez de place pour : {itemData.itemName}");
            }
        }
    }
}
